### ISSUE TITLE
Few suggestions

### ISSUE THREAD

**Issue by HongChenTW** [rickkvm/fops-task#17]
Hi @rickkvm , this is Hong from Trend Micro, thanks for your works and there are few suggestions:

# Suggestions

## 1. Required Flag

In both `linecount` & `checksum` subcommands, `file` flag are required, you can directly leverage cobra ability to mark `file` flag as required.

## 2. Constant variables auto increment

https://github.com/rickkvm/fops-task/blob/58c2f3b3d55350f9312d9b277a0374beb11f8df2/checksum/checksum.go#L15-L19

You can leverage golang's predeclared identifier `iota`[1] for handling auto increment constant variables gracefully.

# References

- [1] https://github.com/golang/go/wiki/Iota

**Comment by rickkvm** [comment]
Hi @HongChenTW,
thanks for your suggestion. I updated the code and close this issue with PR #20 .
Any other suggestions are welcome.
