### ISSUE TITLE
binary file detection

### ISSUE THREAD

**Issue by rybbchao** [rickkvm/fops-task#18]
Hi, @rickkvm. This is Duncan from Trend Micro.

Command `linecount` should print error message for binary file.

```
$ fops linecount -f fops
error: Cannot do linecount for binary file 'fops'
```

If possible, please revise your implementation. Thanks!

**Comment by rickkvm** [comment]
Hi @rybbchao ,
Thank you for reviewing the code.
This issue is fix in #21 PR. I count separators by chunks-by-chunks instead of read them all into memory.
And have a binary detection before doing linecount.
